export { default as Home } from './Home/Home'
export { default as About } from './About/About'
export { default as Services } from './Services/Services'
export { default as Team } from './Team/Team'
export { default as Support } from './Support/Support'
export { default as Clients } from './Clients/Clients'